services:
  db:
    image: postgres:16
    container_name: smartpolls-db
    environment:
      POSTGRES_DB: smartpolls
      POSTGRES_USER: smartpolls
      POSTGRES_PASSWORD: smartpolls
    ports:
      - "5432:5432"
    volumes:
      - smartpolls_pgdata:/var/lib/postgresql/data

volumes:
  smartpolls_pgdata:
