server:
  port: 8080

spring:
  application:
    name: smartpolls-api

  datasource:
    url: jdbc:postgresql://localhost:5432/smartpolls
    username: smartpolls
    password: smartpolls

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
