server:
  port: ${PORT:8080}

spring:
  application:
    name: smartpolls-api

  datasource:
    url: ${SPRING_DATASOURCE_URL:${DB_URL:${JDBC_DATABASE_URL:}}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:}}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info